import { defineEventHandler } from 'h3'
import type { Company } from '~/types/company'

// Helper function to create slug
const createSlug = (id: number, name: string): string => {
  return `${id}-${name.toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')}`
}

// Mock data for companies
export const companies: Company[] = [
  {
    id: 1,
    name: 'ООО "ТехноПром"',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'manufacturer',
    slug: createSlug(1, 'ООО "ТехноПром"'),
    tradeActivity: 'Продавец',
    businessType: 'Производство товаров',
    activityType: 'Производство промышленного оборудования',
    description: 'Ведущий производитель промышленного оборудования в России',
    country: 'Россия',
    federalDistrict: 'Центральный',
    region: 'Московская область',
    city: 'Москва',
    fullName: 'Общество с ограниченной ответственностью "ТехноПром"',
    inn: '1234567890',
    ogrn: '1234567890123',
    kpp: '123456789',
    registrationDate: '2010-01-15',
    legalAddress: 'г. Москва, ул. Промышленная, д. 1',
    productionAddress: 'г. Москва, ул. Заводская, д. 10',
    phone: '+7 (495) 123-45-67',
    email: 'info@techprom.ru',
    website: 'www.techprom.ru'
  },
  {
    id: 2,
    name: 'СтройСервис',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'service',
    slug: createSlug(2, 'СтройСервис'),
    tradeActivity: 'Покупатель и продавец',
    businessType: 'Оказание услуг',
    activityType: 'Строительные услуги',
    description: 'Комплексные строительные услуги под ключ',
    country: 'Россия',
    federalDistrict: 'Северо-Западный',
    region: 'Санкт-Петербург',
    city: 'Санкт-Петербург',
    fullName: 'ООО "СтройСервис"',
    inn: '0987654321',
    ogrn: '3210987654321',
    kpp: '987654321',
    registrationDate: '2015-03-20',
    legalAddress: 'г. Санкт-Петербург, ул. Строителей, д. 5',
    productionAddress: 'г. Санкт-Петербург, ул. Строителей, д. 5',
    phone: '+7 (812) 987-65-43',
    email: 'info@stroyservice.ru',
    website: 'www.stroyservice.ru'
  },
  {
    id: 3,
    name: 'ИнноТех',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'manufacturer',
    slug: createSlug(3, 'ИнноТех'),
    tradeActivity: 'Покупатель и продавец',
    businessType: 'Производство товаров и оказание услуг',
    activityType: 'Разработка и производство электроники',
    description: 'Инновационные решения в области электроники и автоматизации',
    country: 'Россия',
    federalDistrict: 'Сибирский',
    region: 'Новосибирская область',
    city: 'Новосибирск',
    fullName: 'ООО "ИнноТех"',
    inn: '5678901234',
    ogrn: '5678901234567',
    kpp: '567890123',
    registrationDate: '2018-07-10',
    legalAddress: 'г. Новосибирск, ул. Инновационная, д. 15',
    productionAddress: 'г. Новосибирск, ул. Технопарковая, д. 3',
    phone: '+7 (383) 456-78-90',
    email: 'contact@innotech.ru',
    website: 'www.innotech.ru'
  },
  {
    id: 4,
    name: 'АгроПром',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'manufacturer',
    slug: createSlug(4, 'АгроПром'),
    tradeActivity: 'Продавец',
    businessType: 'Производство товаров',
    activityType: 'Сельскохозяйственное производство',
    description: 'Крупнейший производитель сельскохозяйственной продукции в регионе',
    country: 'Россия',
    federalDistrict: 'Южный',
    region: 'Краснодарский край',
    city: 'Краснодар',
    fullName: 'АО "АгроПром"',
    inn: '6789012345',
    ogrn: '6789012345678',
    kpp: '678901234',
    registrationDate: '2005-05-25',
    legalAddress: 'г. Краснодар, ул. Полевая, д. 7',
    productionAddress: 'Краснодарский край, с. Урожайное, ул. Центральная, д. 1',
    phone: '+7 (861) 234-56-78',
    email: 'info@agroprom.ru',
    website: 'www.agroprom.ru'
  },
  {
    id: 5,
    name: 'МедТехника',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'manufacturer',
    slug: createSlug(5, 'МедТехника'),
    tradeActivity: 'Продавец',
    businessType: 'Производство товаров',
    activityType: 'Медицинское оборудование',
    description: 'Разработка и производство современного медицинского оборудования',
    country: 'Россия',
    federalDistrict: 'Уральский',
    region: 'Свердловская область',
    city: 'Екатеринбург',
    fullName: 'ООО "МедТехника"',
    inn: '7890123456',
    ogrn: '7890123456789',
    kpp: '789012345',
    registrationDate: '2012-09-03',
    legalAddress: 'г. Екатеринбург, ул. Медицинская, д. 12',
    productionAddress: 'г. Екатеринбург, ул. Промышленная, д. 45',
    phone: '+7 (343) 345-67-89',
    email: 'contact@medtech.ru',
    website: 'www.medtech.ru'
  },
  {
    id: 6,
    name: 'ЭкоПродукт',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'manufacturer',
    slug: createSlug(6, 'ЭкоПродукт'),
    tradeActivity: 'Продавец',
    businessType: 'Производство товаров',
    activityType: 'Пищевая промышленность',
    description: 'Производство экологически чистых продуктов питания',
    country: 'Россия',
    federalDistrict: 'Приволжский',
    region: 'Республика Татарстан',
    city: 'Казань',
    fullName: 'ООО "ЭкоПродукт"',
    inn: '8901234567',
    ogrn: '8901234567890',
    kpp: '890123456',
    registrationDate: '2016-11-15',
    legalAddress: 'г. Казань, ул. Экологическая, д. 8',
    productionAddress: 'г. Казань, ул. Фабричная, д. 23',
    phone: '+7 (843) 567-89-01',
    email: 'info@ecoproduct.ru',
    website: 'www.ecoproduct.ru'
  },
  {
    id: 7,
    name: 'ТрансЛогистик',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'service',
    slug: createSlug(7, 'ТрансЛогистик'),
    tradeActivity: 'Покупатель',
    businessType: 'Оказание услуг',
    activityType: 'Транспортные услуги',
    description: 'Комплексные логистические решения для бизнеса',
    country: 'Россия',
    federalDistrict: 'Дальневосточный',
    region: 'Приморский край',
    city: 'Владивосток',
    fullName: 'ООО "ТрансЛогистик"',
    inn: '9012345678',
    ogrn: '9012345678901',
    kpp: '901234567',
    registrationDate: '2014-04-22',
    legalAddress: 'г. Владивосток, ул. Портовая, д. 17',
    productionAddress: 'г. Владивосток, ул. Портовая, д. 17',
    phone: '+7 (423) 678-90-12',
    email: 'info@translogistic.ru',
    website: 'www.translogistic.ru'
  },
  {
    id: 8,
    name: 'ИТ-Консалтинг',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'service',
    slug: createSlug(8, 'ИТ-Консалтинг'),
    tradeActivity: 'Продавец',
    businessType: 'Оказание услуг',
    activityType: 'Информационные технологии',
    description: 'Профессиональные ИТ-услуги для бизнеса любого масштаба',
    country: 'Россия',
    federalDistrict: 'Центральный',
    region: 'Москва',
    city: 'Москва',
    fullName: 'ООО "ИТ-Консалтинг"',
    inn: '0123456789',
    ogrn: '0123456789012',
    kpp: '012345678',
    registrationDate: '2017-08-30',
    legalAddress: 'г. Москва, ул. Цифровая, д. 5',
    productionAddress: 'г. Москва, ул. Цифровая, д. 5',
    phone: '+7 (495) 789-01-23',
    email: 'contact@itconsulting.ru',
    website: 'www.itconsulting.ru'
  },
  {
    id: 9,
    name: 'ЭнергоСтрой',
    logo: 'https://banner2.cleanpng.com/20181124/av/kisspng-comcast-business-organization-computer-icons-email-5bf8ef2b040795.9053466915430408110165.jpg',
    type: 'service',
    slug: createSlug(9, 'ЭнергоСтрой'),
    tradeActivity: 'Покупатель и продавец',
    businessType: 'Производство товаров и оказание услуг',
    activityType: 'Энергетическое строительство',
    description: 'Проектирование и строительство энергетических объектов',
    country: 'Россия',
    federalDistrict: 'Центральный',
    region: 'Московская область',
    city: 'Москва',
    fullName: 'ООО "ЭнергоСтрой"',
    inn: '1234567890',
    ogrn: '1234567890123',
    kpp: '123456789',
    registrationDate: '2010-01-15',
    legalAddress: 'г. Москва, ул. Энергетическая, д. 20',
    productionAddress: 'г. Москва, ул. Энергетическая, д. 20',
    phone: '+7 (495) 123-45-67',
    email: 'info@energostroy.ru',
    website: 'www.energostroy.ru'
  }
]

export default defineEventHandler(() => {
  // Simulate a slight delay to mimic real API behavior
  return new Promise<Company[]>((resolve) => {
    setTimeout(() => {
      resolve(companies)
    }, 300)
  })
})