#!/bin/bash

echo "=== Восстановление базы данных на сервере ==="
echo ""
echo "Шаги для выполнения на сервере:"
echo ""
echo "1. Подключитесь к серверу:"
echo "   ssh root@77.222.47.33"
echo ""
echo "2. Перейдите в директорию с дампом:"
echo "   cd /root/buisnes_kufar"
echo ""
echo "3. Создайте резервную копию существующей базы (ВАЖНО!):"
echo "   docker exec buisnes_kufar-db-1 pg_dump -U postgres buisnes_kufar > backup_before_restore_\$(date +%Y%m%d_%H%M%S).sql"
echo ""
echo "4. Восстановите базу данных:"
echo "   cat backup_20251026_143805.sql | docker exec -i buisnes_kufar-db-1 psql -U postgres -d buisnes_kufar"
echo ""
echo "Или альтернативный способ:"
echo "   docker cp backup_20251026_143805.sql buisnes_kufar-db-1:/tmp/backup.sql"
echo "   docker exec -i buisnes_kufar-db-1 psql -U postgres -d buisnes_kufar -f /tmp/backup.sql"
echo ""
echo "=== Готово! ==="
