services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
      DEV_REDIRECT_URL: "http://frontend:3000"
    volumes:
      - ./logs/backend:/app/logging
      - ./backend/cache:/app/cache
      - ./backend/database.db:/app/database.db
      - ./backend/uploads:/app/uploads
      - ./backend/app/static:/app/app/static
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/webroot:/var/www/html
      - ./backend/uploads:/app/uploads
      - ./backend/app/static:/usr/share/nginx/html/static
    depends_on:
      - backend
      - frontend
      -
  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      # задаем переменные среды
      args:
        DOMAIN_EMAIL: Dmitriy40647274@gmail.com
        DOMAIN_URL: https://tradesynergy.ru

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    ports:
#      - "5050:5050"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: dmitriy40647274@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: adminKufar2398

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    command: >
      -c shared_buffers=512MB
      -c max_connections=200
      -c idle_in_transaction_session_timeout=10s
      -c tcp_keepalives_idle=60
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached