export const enum QueryKeys {
	BUYER_DEALS = 'buyer-deals',
	SELLER_DEALS = 'seller-deals',
	DEALS_BY_IDS = 'deals-by-ids',
	DEAL_BY_ID = 'deal-by-id',
	UPDATE_DEAL_BY_ID = 'update-deal-by-id',
	UNITS_OF_MEASUREMENT = 'units-of-measurement',
	CREATE_BILL = 'create-bill',
	CREATE_CONTRACT = 'create-contract',
	CREATE_SUPPLY_CONTRACT = 'create-supply-contract',
	CREATE_ORDER_FROM_CHECKOUT = 'create-order-from-checkout',
	GET_UNITS_MEASUREMENT = 'get-units-measurement',
	DELETE_DEAL_BY_ID = 'delete-deal-by-id',
	CREATE_NEW_DEAL_VERSION = 'create-new-deal-version',
	DELETE_LAST_DEAL_VERSION = 'delete-last-deal-version',
	GET_MY_COMPANY = 'get-my-company',
	GET_DOCUMENTS_BY_DEAL_ID = 'get-documents-by-deal-id',
	UPLOAD_DOCUMENT_BY_DEAL_ID = 'upload-document-by-deal-id',
	DOWNLOAD_DOCUMENT = 'download-document',
	DELETE_DOCUMENT_BY_DEAL_ID = 'delete-document-by-deal-id',
}