"""add official to supply contract obj

Revision ID: 2e9c77d64f91
Revises: 8391f9271add
Create Date: 2026-04-29 15:13:07.807844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e9c77d64f91'
down_revision: Union[str, None] = '8391f9271add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("supply_contract_officials", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("orders", "supply_contract_officials")
    # ### end Alembic commands ###
