"""Update messages table structure for chat system

Revision ID: 54fd3ac7b629
Revises: 714a6c8a09e2
Create Date: 2025-06-25 23:00:57.470938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fd3ac7b629'
down_revision: Union[str, None] = '714a6c8a09e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('sender_company_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('sender_user_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('messages', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint(op.f('messages_to_company_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_from_company_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'companies', ['sender_company_id'], ['id'])
    op.drop_column('messages', 'subject')
    op.drop_column('messages', 'from_company_id')
    op.drop_column('messages', 'to_company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('to_company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('from_company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_from_company_id_fkey'), 'messages', 'companies', ['from_company_id'], ['id'])
    op.create_foreign_key(op.f('messages_to_company_id_fkey'), 'messages', 'companies', ['to_company_id'], ['id'])
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'file_type')
    op.drop_column('messages', 'file_size')
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'file_path')
    op.drop_column('messages', 'sender_user_id')
    op.drop_column('messages', 'sender_company_id')
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###
