"""empty message

Revision ID: 6c50c32257ff
Revises: d16f14d07843
Create Date: 2025-07-04 14:42:04.361229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c50c32257ff'
down_revision: Union[str, None] = 'd16f14d07843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'inn',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('companies', 'ogrn',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['inn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('companies', 'ogrn',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('companies', 'inn',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
