"""add official base document fields

Revision ID: 8391f9271add
Revises: add_tot_excl_vat
Create Date: 2026-04-29 09:43:31.403545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8391f9271add'
down_revision: Union[str, None] = 'add_tot_excl_vat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_officials', sa.Column('is_base', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('company_officials', sa.Column('base_document', sa.String(length=255), nullable=True))
    op.add_column('company_officials', sa.Column('base_document_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_officials', 'base_document_name')
    op.drop_column('company_officials', 'base_document')
    op.drop_column('company_officials', 'is_base')
    