"""empty message

Revision ID: d16f14d07843
Revises: 
Create Date: 2025-07-04 13:33:37.744017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16f14d07843'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. При пустой БД создаём все таблицы из моделей (bootstrap)."""
    conn = op.get_bind()
    companies_exists = conn.execute(
        sa.text("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'companies')")
    ).scalar()
    if not companies_exists:
        from app.db.base_class import Base
        from app.api.authentication.models import user  # noqa: F401
        from app.api.company.models import company  # noqa: F401
        from app.api.company.models import official, announcement  # noqa: F401
        from app.api.products.models import product  # noqa: F401
        from app.api.common.models import country, federal_district, region, city  # noqa: F401
        from app.api.chats.models import chat, chat_participant  # noqa: F401
        from app.api.messages.models import message  # noqa: F401
        from app.api.authentication.models import employee  # noqa: F401
        Base.metadata.create_all(bind=conn)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
