FROM nginx:latest

# Удаляем дефолтную конфигурацию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем локальную конфигурацию как default.conf
COPY nginx.local.conf /etc/nginx/conf.d/default.conf

# Создаем директорию для загрузок
RUN mkdir -p /app/uploads
